services:
  backend:
    container_name: mav_backend
    image: ghcr.io/yellowsoar/musical_activity_viewer:latest
    ports:
      - 0.0.0.0:8000:8000
      - 0.0.0.0:8888:80
      - 0.0.0.0:9001:9001
      # supervisord
    env_file:
      - ../.env
    depends_on:
      - mongodb

  # https://hub.docker.com/r/mongodb/mongodb-community-server/tags?page=&page_size=&ordering=&name=4.
  mongodb:
    container_name: mav_mongodb
    image: mongodb/mongodb-community-server:4.4.8-ubuntu2004
    # AVX issue
    # https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
    restart: always
    ports:
      - 0.0.0.0:27017:27017
    command: mongod --dbpath /tmp

  # https://hub.docker.com/_/mongo-express
  mongo-express:
    container_name: mav_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ../.env
    depends_on:
      - mongodb
